## 作業

練習以旋轉變換 + 平移變換來實現仿射變換
> 旋轉 45 度 + 縮放 0.5 倍 + 平移 (x+100, y-50)

In [2]:
import cv2
import numpy as np

# Using lena.png
img = 'img/lena.png'

# default read as cv2.IMREAD_COLOR(彩色圖)
img_bgr = cv2.imread(img, cv2.IMREAD_COLOR)

In [4]:
# case 1
# img_equal.shape[0] means height, img_equal.shape[1] means width (512, 512)
h, w = img_bgr.shape[0:2]

# get a rotation matrix(旋轉矩陣) -> ((center), rotate angle, scale)
M_rotate = cv2.getRotationMatrix2D((w/2, h/2), 45, 0.5)
print('rotation matrix :')
print(M_rotate)

# get a translation transformation matrix(平移矩陣) -> (x+100, y-50)
M_translate = np.float32([[1, 0, 100], [0, 1, -50]])
print('translation matrix :')
print(M_translate)

# image rotate :
# cv2.warpAffine(img, TT Matrix, dsize=(width, height))
img_rotate = cv2.warpAffine(img_bgr, M_rotate, (w, h))

# image translate :
# cv2.warpAffine(img, TT Matrix, dsize=(width, height))
img_rotate_translate = cv2.warpAffine(img_rotate, M_translate, (w, h))

# 橫向組合圖片
img_rotate_translate_new = np.hstack((img_bgr, img_rotate, img_rotate_translate))

while True :
    # display of img_rotate_translate_new, named as 'img rotate 45 & scale 0.5 & translate x+100, y-50'
    cv2.imshow('img rotate 45 & scale 0.5 & translate x+100, y-50', img_rotate_translate_new)
    
    # waiting until to press any key then close the display window
    if cv2.waitKey(0) : 
        cv2.destroyAllWindows()
        break

rotation matrix :
[[  0.35355339   0.35355339  74.98066402]
 [ -0.35355339   0.35355339 256.        ]]
translation matrix :
[[  1.   0. 100.]
 [  0.   1. -50.]]
