## 作業

練習以旋轉變換 + 平移變換來實現仿射變換
> 旋轉 45 度 + 縮放 0.5 倍 + 平移 (x+100, y-50)

In [1]:
import cv2
import numpy as np

# Using lena.png
img = 'img/lena.png'

# default read as cv2.IMREAD_COLOR(彩色圖)
img_bgr = cv2.imread(img, cv2.IMREAD_COLOR)

In [2]:
# case 1
# img_equal.shape[0] means height, img_equal.shape[1] means width (512, 512)
h, w = img_bgr.shape[0:2]

# get a rotation matrix(旋轉矩陣) -> ((center), rotate angle, scale)
M_rotate = cv2.getRotationMatrix2D((w/2, h/2), 45, 0.5)
print('rotation matrix :')
print(M_rotate)

# get a translation transformation matrix(平移矩陣) -> (x+100, y-50)
M_translate = np.float32([[1, 0, 100], [0, 1, -50]])
print('translation matrix :')
print(M_translate)

# image rotate :
# cv2.warpAffine(img, TT Matrix, dsize=(width, height))
img_rotate = cv2.warpAffine(img_bgr, M_rotate, (w, h))

# image translate :
# cv2.warpAffine(img, TT Matrix, dsize=(width, height))
img_rotate_translate = cv2.warpAffine(img_rotate, M_translate, (w, h))

# 橫向組合圖片
img_rotate_translate_new = np.hstack((img_bgr, img_rotate, img_rotate_translate))

while True :
    # display of img_rotate_translate_new, named as 'img rotate 45 & scale 0.5 & translate x+100, y-50'
    cv2.imshow('img rotate 45 & scale 0.5 & translate x+100, y-50', img_rotate_translate_new)
    
    # waiting until to press any key then close the display window
    if cv2.waitKey(0) : 
        cv2.destroyAllWindows()
        break

rotation matrix :
[[  0.35355339   0.35355339  74.98066402]
 [ -0.35355339   0.35355339 256.        ]]
translation matrix :
[[  1.   0. 100.]
 [  0.   1. -50.]]


In [3]:
# case 2
# img_equal.shape[0] means height, img_equal.shape[1] means width (512, 512)
h, w = img_bgr.shape[0:2]

# define 3 points of (x,y) coordinate, then get Affine transformation
pt1 = np.float32([[50,50], [300,100], [200,300]])
pt2 = np.float32([[80,80], [330,150], [300,300]])
# get Affine Matrix : M
M = cv2.getAffineTransform(pt1, pt2)  
# Affine transformation
img_affine = cv2.warpAffine(img_bgr, M, (w, h))

# annotate on image
img_copy = img_bgr.copy()
for idx, pts in enumerate(pt1):
    pts = tuple(map(int, pts))  # map(int, pts) -> 把pts的每個元素轉成 int type
    cv2.circle(img_copy, pts, 3, (0, 255, 0), -1)  # cv2.circle(img, 圓心, 半徑, 顏色, 線寬)
    # cv2.putText(img, 加上的文字, 文字的(x,y)座標, 字形, 字體大小, 字體的顏色, 字體的寬度)
    cv2.putText(img_copy, str(idx), (pts[0]+5, pts[1]+5), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 0), 1)

for idx, pts in enumerate(pt2):
    pts = tuple(map(int, pts))
    cv2.circle(img_affine, pts, 3, (255, 0, 0), -1)
    cv2.putText(img_affine, str(idx), (pts[0]+5, pts[1]+5), cv2.FONT_HERSHEY_COMPLEX, 1, (255, 0, 0), 1)

# 橫向組合圖片
img_affine_new = np.hstack((img_copy, img_affine))

while True :
    # display of img_affine_new, named as 'image affine'
    cv2.imshow('image affine', img_affine_new)
    
    # waiting until to press any key then close the display window
    if cv2.waitKey(0) : 
        cv2.destroyAllWindows()
        break